### PR TITLE
Improvements to PIPE invariant algorithm

### PR DESCRIPTION
**Pull request by yanntm**
Refactor code for phase 2 of PIPE algorithm to work with a *set* of
normalized columns. This avoids heavy construction/destruction costs
from working with a matrix stored in row format to add/remove columns
repeatedly. 
Also remove columns which have become useless from further consideration
during computation.
Finally there is a small heuristic to select the next row : take the row with least constraints on it first. Original paper suggests "take row such that there will be fewest negatives in result", this heuristic does not precisely match that, but in practice is pretty close in effects. Previous code selected basically the first row with a negative value (i.e. no heuristic at all).

Note that this also fixes some basically divergent behaviors from the current solver, where the same columns were redundantly inserted into the matrix matB. This is now tested on the fly by the Set properties.
My test model was a rather large model Vasy2003 described here : http://mcc.lip6.fr/models.php
You can get the pnml to test with apt from that page. Basically the current solver ran out of memory and time. This version handles it in less than a second. A corresponding test with a few chosen S invariants has been added to the test suite. It fails before patch or with FARKAS setting...

Improvements are integrated in our forked version of this at :
https://github.com/lip6/ITSTools/tree/master/smt/fr.lip6.move.gal.gal2smt/src/uniol/apt/analysis/invariants
This commit is to feedback the nice improvements back to apt group, we will continue working with our forked version, I'll feedback any further critical improvements we might implement.
thanks for making that code public in the first place.

### CODE REVIEW

**Comment by psychon** [comment]
Thanks a lot for this. I'll see if I get can Manuel (the original author of this code) to look at it. Also, thanks for "pointing at me" in a commit message. I looked a bit around, but so far I didn't really understand what your code is trying to do over there. ;-)

**Comment by yanntm** [comment]
Hi

I've optimized also phase 1 of the algorithm in my version, you might want to merge that too.
see commit https://github.com/lip6/ITSTools/commit/f01d4c402e08681734d91784b2ae7b81d05ac322

Sorry, it's abit of work to format the changes to build a pull request though.

**Comment by psychon** [comment]
@yanntm Thanks a lot. I guess we should first handle this pull request and then look at your other improvements. We still did not have the time to look closely at this, sorry. If you want and don't mind, I could afterwards also copy over your changes and create a pull request for that, so you do not have to do that.

**Comment by yanntm** [comment]
Hi
Well I think you could use the commit as a patch guideline, but there are some commits before it (e.g. refactor phase 1 to a function, some API change so you can break with Flows (pos or neg in sum, but guaranteed polyomila) not positive semi flows (only positive sums, exponential on some examples)

If you decide to integrate the first patch, and that additional commit is hard to integrate I'll merge it in with another pull request, it'll be easier for me I know what I was doing. 

But I don't want to make the effort if the pulls are rejected at some point.

**Comment by yanntm** [comment]
just to document the phase 1 optimizations in that patch :
 
* use BitSet instead of List<Integer> to represent sets in Pppm struct and propagated to all usage thereof. While it is not sparse, it is very much smaller in memory (the generic Integer hurts!) and faster to manipulate in practice.
* avoid recomputing at every loop the Ppm for each row, instead maintain their states by updating them in place as columns are removed. This removes basically a quadratic (col*col) in the complexity, since worst case we remove all columns by pairs (col/2 loop iterations) but each computation of ppm is (row*col) since we visit the whole matrix.

JProfiler rocks btw,  you should try it, nice tool.

**Comment by psychon** [comment]
> the pulls are rejected at some point.

Well, this is some "math magic" going on that I haven't looked into yet and that we want to get right. I doubt a lot that we will plain reject this. The more likely option (which I still consider unlikely) is something like "this part does not always work correctly / may produce the wrong result".

> JProfiler rocks btw, you should try it, nice tool.

Thanks for the hint. So far I always end up using VisualVM.

**Comment by yanntm** [comment]
Hi, well it's not really algorithmic changes, just pure optimization, i.e. running the same algorithm more efficiently.

The only change I did to the algorithm is the heurisitc that chooses the next row in phase 2.
That changes iteration order (hence overall complexity)  and is heuristic.

The rest is purely using more appropriate data structures, avoid recomputing.... 
no changes to the algorithm.

So no real math magic, I'm not using tricks to reduce the matrix faster or anything.

Just plain Java implementation magic, + a large benchmark that helps identify bottlenecks on corner cases + a good profiler.

Visual VM is not bad, but I really like the "call hot spot" and "allocation hot spot" features of JProfiler + overall ergonomy. They give you licenses if you say you're doing open source.

**Comment by psychon** [comment]
> Hi, well it's not really algorithmic changes, just pure optimization, i.e. running the same algorithm more efficiently.

Ah, that hint helped to understand what you did. It also made the changes sound less dangerous.

Thanks for your patches!

**Comment by yanntm** [comment]
well ok, now I have to format the other patch, :)

I'll do it this week, maybe add a couple of tests in that showcase it.

maybe I'll leave the sets of Int rather than BitSet and just propagate the real algorithmic change, i.e. calcPppm outside the while loop. The List<Integer>Int appeared as a bottleneck at first, but it's only because it was called so many times in calcPppm.
The Sparse representation offered by List<Int> might actually do better in some cases, I havn't tested.

or not, as you prefer, the BitSet are already used in that other patch to represent sets anyway.

cheers, thanks for accepting my patch, please consider participating in the Model Checking Contest next year, because, why not ? you already have a PNML parser.

http://mcc.lip6.fr

I'm using the invariants computation as part of my ITS-tools submission there.

**Comment by psychon** [comment]
> well ok, now I have to format the other patch, :)

Thanks. I promise to be quicker this time. "This (not specially crafted) example is solved a thousand times faster" is quite a convincing argument. :)

> cheers, thanks for accepting my patch, please consider participating in the Model Checking Contest next year, because, why not ? you already have a PNML parser.

Thanks for the suggestion, but I do not think APT is competitive here. We could participate in StateSpace, UpperBounds and Reachability, I guess, but just use JProfiler to look at the hotspots of APT computing a reachability graph (I would expect our inefficient check of "is this transition firable" to be the result). Also, other tools specialise in a specific problem way more while APT (I think) is more of an "everything goes" without as much tricks in its sleeve and would just compute the whole reachability graph.

(Heh, we could even participate in the CTL and LTL categories. https://github.com/CvO-Theory/apt-modal-mu-synthesis has code related to the modal mu-calculus, so we would "just" have to translate CTL and LTL into the mu-calculus. Surely, that will be quite efficient. ;) )

**Comment by yanntm** [comment]
Hi,

well generating the state space graph is kind of the point for a model-checker, and translating to mu-calc is pretty standard, it's what LTSmin does, or Tina from LAAS (rather the more modern [SELT](http://projects.laas.fr/tina/manuals/selt.html) of the toolbox) which are both explicit state model-checkers. Java is pretty fast, the issue is more memory wise, it does not show up well to C/C++. 
I understand that apt is more of a general toolbox than optimized to do one thing very well, but still.confronting to other tools is a healthy experience (e.g. it helps find bugs).

Anyway, I'll build another patch request.

**Comment by psychon** [comment]
> I understand that apt is more of a general toolbox than optimized to do one thing very well, but still.confronting to other tools is a healthy experience (e.g. it helps find bugs).

I only looked at one example: http://mcc.lip6.fr/pdf/Kanban-form.pdf

APT can generate the state graph of kanban-3 in about 2 seconds and kanban-4 in about 17 seconds, but runs into an OOM for kanban-5 (Java's memory limit was 4GiB). So a rough guess for kanban-5 would be 153 seconds.
If I understand http://mcc.lip6.fr/2016/index.php?CONTENT=results/exec_r157kn-blw3-146416412400100.php&TITLE=Execution%20of%20r157kn-blw3-146416412400100 correctly, ITS-Tools handles kanban-5 in less than 8 seconds.

Since kanban-5 is the smallest size considered by the MCC, APT would more or less fail to participate here.

> Anyway, I'll build another patch request.

Thanks

**Comment by yanntm** [comment]
On the patch:
well, I went a bit overboard on my fork, I've included some sparse representation I took from google.
It fits in 4 files roughly, but it's bit of a dependency.
I'm not sure you'd want that, so I'll stick to my earlier idea of just integrating the computePpPm outside the loop in a pull request.

Thanks for the bug on isSingleBit.

On the MCC:
Yeah the runtime in that run reads
Kanban\_PT\_0005\_flat,2.54643e+06,0.02426
that's 24 ms for actual model-checking (without preprocessing)
But then I'm winning that category, I have to have some tricks :)

kanban is maybe not the best example, it does explode pretty fast, you need partial order reduction to tackle it in explicit basically. It does not mean you could not answer reachability queries on it, e.g. just using the invariants can contradict reachability assertions.
Lola is a very successful explicit tool, though they do have some nice "tricks", they don't participate in StateSpace category. They win reachability categories, by a pretty wide margin.
In that category, pretty much Symbolic methods are crushing everything else (ITSTools, pnmc, marcie), but that does not mean symbolic wins on other queries. You have a large set of algorithms available, you could run reachability with state space construction but also test sufficient conditions using your nice set of structural algorithms.
Like the category deadlock, maybe you could compete in that, you have traps/syphons/ the works available.
Anyway, I won't lie it's a **bit** of work to integrate and submit a solution to the contest, but you have a lot of ingredients.

**Pull request merged**
